package com.example.studentmysqlandjdbc.controller;

import com.example.studentmysqlandjdbc.model.Student;
import com.example.studentmysqlandjdbc.repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.util.List;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/students")
    public List<Student> students(){
        return studentRepository.findAll();
    }

    @GetMapping("/testStudent")
    public List<Student> testStudent() {
        List<Student> studentList= studentRepository.findAll();
        Student std = new Student();
        std.setName("autogeneratedName" + studentList.size() );
        std.setBornTime(LocalDate.now());
        std.setBornDate(LocalDate.now());
        studentList.add(std);
        studentRepository.save(std);
        return studentList;
    }

}
